version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.3
  clojure: lambdaisland/clojure@0.0.8

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          steps:
            - run: npm install ws
            - kaocha/execute:
                args: "--reporter documentation"
                clojure_version: << parameters.clojure_version >>

jobs:
  test:
    parameters:
      os:
        type: executor
      clojure_version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout_and_run:
          clojure_version: << parameters.clojure_version >>


workflows:
  kaocha_test:
    jobs:
      - test:
          matrix:
            parameters:
              os: [clojure/openjdk17, clojure/openjdk15, clojure/openjdk11, clojure/openjdk8]
              clojure_version: ["1.10.3", "1.11.1"]
