version: 2.1

orbs:
  kaocha: lambdaisland/kaocha@0.0.1
  clojure: lambdaisland/clojure@0.0.6

commands:
  checkout_and_run:
    parameters:
      clojure_version:
        type: string
    steps:
      - checkout
      - clojure/with_cache:
          steps:
            - run: npm install ws
            - kaocha/execute:
                args: "--reporter documentation"
                clojure_version: << parameters.clojure_version >>

jobs:
  java-15-clojure-1_10:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-11-clojure-1_10:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-8-clojure-1_10:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.10.2"}}]

  java-15-clojure-1_9:
    executor: clojure/openjdk15
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

  java-11-clojure-1_9:
    executor: clojure/openjdk11
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]

  java-8-clojure-1_9:
    executor: clojure/openjdk8
    steps: [{checkout_and_run: {clojure_version: "1.9.0"}}]
  test:
    parameters:
      os:
        type: executor
      clojure_version:
        type: string
    executor: << parameters.os >>
    steps:
      - checkout_and_run:
          clojure_version: << parameters.clojure_version >>


workflows:
  kaocha_test:
    jobs:
      - test:
          matrix:
            parameters:
              os: [clojure/openjdk17, clojure/openjdk15, clojure/openjdk11, clojure/openjdk8]
              clojure_version: ["1.10.3", "1.11.1"]
      # - java-15-clojure-1_10
      # - java-11-clojure-1_10
      # - java-8-clojure-1_10
      # - java-15-clojure-1_9
      # - java-11-clojure-1_9
      # - java-8-clojure-1_9
